### PR TITLE
don’t minify files that already advertise as minified.

### PR DESCRIPTION
**Pull request by stefanpenner**
just an idea, curious what others think.

We could also detect the content of the file seems sufficiently minified and skip it?

### CODE REVIEW

**Comment by stefanpenner** [comment]
@ef4 r?

**Comment by ef4** [comment]
:+1:

**Comment by stefanpenner** [comment]
@ef4 do you think its worth it, to read the contents of files and see if they look minified?

**Comment by rwjblue** [comment]
Broke Ember's build :crying_cat_face:

**Comment by rwjblue** [comment]
Basically, in emberjs-build we copy `ember.prod.js` to `ember.min.js` then we minify.  I'll work on getting that updated (because its pretty crazy now ;P).

**Pull request merged**
